flowchart TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["-"]) -->|crm:P190_has_symbolic_content| 1(["''Immigrated to Canada in 1924''@en"]):::Literal
0(["-"]) -->|crm:P2_has_type| 2(["vocab:100147"])
2(["vocab:100147"]) -->|rdfs:label| 3(["''Note curatoriale''@fr"]):::Literal
4(["-"]):::E28_Conceptual_Object_URI -->|rdf:type| 5["crm:E33_Linguistic_Object"]:::E28_Conceptual_Object
2(["vocab:100147"]) -->|rdfs:label| 6(["''Curatorial Note''@en"]):::Literal
7(["vocab:2001"]) -->|rdfs:label| 8(["''Anglais''@fr"]):::Literal
4(["-"]) -->|crm:P2_has_type| 2(["vocab:100147"])
7(["vocab:2001"]) -->|rdfs:label| 9(["''English''@en"]):::Literal
10(["actor:0001_100"]) -->|rdfs:label| 11(["''Yousuf Karsh (1908-2002)''@en"]):::Literal
12(["vocab:2003"]) -->|rdfs:label| 13(["''Français''@fr"]):::Literal
10(["actor:0001_100"]):::E39_Actor_URI -->|rdf:type| 14["crm:E21_Person"]:::E39_Actor
12(["vocab:2003"]) -->|rdfs:label| 15(["''French''@en"]):::Literal
7(["vocab:2001"]):::E55_Type_URI -->|rdf:type| 16["crm:E56_Language"]:::E55_Type
10(["actor:0001_100"]) -->|crm:P67i_is_referred_to_by| 4(["-"])
0(["-"]):::E28_Conceptual_Object_URI -->|rdf:type| 17["crm:E33_Linguistic_Object"]:::E28_Conceptual_Object
0(["-"]) -->|crm:P72_has_language| 7(["vocab:2001"])
10(["actor:0001_100"]) -->|crm:P67i_is_referred_to_by| 0(["-"])
4(["-"]) -->|crm:P72_has_language| 12(["vocab:2003"])
2(["vocab:100147"]):::E55_Type_URI -->|rdf:type| 18["crm:E55_Type"]:::E55_Type
4(["-"]) -->|crm:P190_has_symbolic_content| 19(["''Immigré au Canada en 1924''@fr"]):::Literal
12(["vocab:2003"]):::E55_Type_URI -->|rdf:type| 20["crm:E56_Language"]:::E55_Type
