flowchart TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["-"]) -->|crm:P7_took_place_at| 1(["vocab:3003"])
1(["vocab:3003"]) -->|rdfs:label| 2(["''Ottawa, CA-ON''@en"]):::Literal
3(["-"]):::E52_Time-Span_URI -->|rdf:type| 4["crm:E52_Time-Span"]:::E52_Time-Span
5(["vocab:100150"]):::E55_Type_URI -->|rdf:type| 6["crm:E55_Type"]:::E55_Type
0(["-"]) -->|crm:P2_has_type| 7(["vocab:100168"])
7(["vocab:100168"]):::E55_Type_URI -->|rdf:type| 8["crm:E55_Type"]:::E55_Type
0(["-"]) -->|crm:P4_has_time-span| 3(["-"])
3(["-"]) -->|crm:P82a_begin_of_the_begin| 9(["''1932-01-01T00:00:00''^^xsd:dateTime"]):::Literal
1(["vocab:3003"]):::E53_Place_URI -->|rdf:type| 10["crm:E53_Place"]:::E53_Place
11(["actor:0001_100"]) -->|rdfs:label| 12(["''Yousuf Karsh (1908-2002)''@en"]):::Literal
11(["actor:0001_100"]):::E39_Actor_URI -->|rdf:type| 13["crm:E21_Person"]:::E39_Actor
7(["vocab:100168"]) -->|crm:P2_has_type| 5(["vocab:100150"])
7(["vocab:100168"]) -->|rdfs:label| 14(["''Photographe''@fr"]):::Literal
3(["-"]) -->|crm:P82b_end_of_the_end| 15(["''1992-12-31T23:59:59''^^xsd:dateTime"]):::Literal
5(["vocab:100150"]) -->|rdfs:label| 16(["''Occupation''@en"]):::Literal
5(["vocab:100150"]) -->|rdfs:label| 17(["''Occupation''@fr"]):::Literal
1(["vocab:3003"]) -->|rdfs:label| 18(["''Ottawa, CA-ON''@fr"]):::Literal
7(["vocab:100168"]) -->|rdfs:label| 19(["''Photographer''@en"]):::Literal
11(["actor:0001_100"]) -->|crm:P14i_performed| 0(["-"])
0(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 20["frbroo:F51_Pursuit"]:::E2_Temporal_Entity
