flowchart TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["-"]) -->|crm:P02_has_range| 1(["actor:0001_124"])
1(["actor:0001_124"]) -->|rdfs:label| 2(["''John William Waterhouse''@en"]):::Literal
3(["object:0001_502"]) -->|crm:P108i_was_produced_by| 4(["-"])
5(["vocab:100180"]):::E55_Type_URI -->|rdf:type| 6["crm:E55_Type"]:::E55_Type
7(["vocab:100143"]) -->|rdfs:label| 8(["''Actor Priority''@en"]):::Literal
5(["vocab:100180"]) -->|rdfs:label| 9(["''Créateur / Créatrice''@fr"]):::Literal
4(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 10["crm:E12_Production"]:::E2_Temporal_Entity
11(["vocab:100144"]) -->|rdfs:label| 12(["''Actor Role''@en"]):::Literal
7(["vocab:100143"]):::E55_Type_URI -->|rdf:type| 13["crm:E55_Type"]:::E55_Type
14(["vocab:1001"]) -->|rdfs:label| 15(["''1''@en"]):::Literal
3(["object:0001_502"]) -->|rdfs:label| 16(["''\''I am half sick of shadows, said The Lady of Shalott\''''@en"]):::Literal
4(["-"]) -->|crm:P01i_is_domain_of| 0(["-"])
11(["vocab:100144"]) -->|rdfs:label| 17(["''Rôle de l'actant''@fr"]):::Literal
1(["actor:0001_124"]):::E39_Actor_URI -->|rdf:type| 18["crm:E21_Person"]:::E39_Actor
14(["vocab:1001"]) -->|rdfs:label| 19(["''1''@fr"]):::Literal
14(["vocab:1001"]) -->|crm:P2_has_type| 7(["vocab:100143"])
0(["-"]):::PC0_Typed_CRM_Property_URI -->|rdf:type| 20["crm:PC14_carried_out_by"]:::PC0_Typed_CRM_Property
21(["-"]) -->|crm:P82a_begin_of_the_begin| 22(["''1915-01-01T00:00:00''^^xsd:dateTime"]):::Literal
21(["-"]) -->|crm:P82b_end_of_the_end| 23(["''1915-12-31T23:59:59''^^xsd:dateTime"]):::Literal
5(["vocab:100180"]) -->|rdfs:label| 24(["''Creator''@en"]):::Literal
4(["-"]) -->|crm:P4_has_time-span| 21(["-"])
21(["-"]):::E52_Time-Span_URI -->|rdf:type| 25["crm:E52_Time-Span"]:::E52_Time-Span
0(["-"]) -->|crm:P14.1_in_the_role_of| 14(["vocab:1001"])
14(["vocab:1001"]):::E55_Type_URI -->|rdf:type| 26["crm:E55_Type"]:::E55_Type
3(["object:0001_502"]):::E18_Physical_Thing_URI -->|rdf:type| 27["crm:E22_Human-Made_Object"]:::E18_Physical_Thing
5(["vocab:100180"]) -->|crm:P2_has_type| 11(["vocab:100144"])
0(["-"]) -->|crm:P14.1_in_the_role_of| 5(["vocab:100180"])
11(["vocab:100144"]):::E55_Type_URI -->|rdf:type| 28["crm:E55_Type"]:::E55_Type
7(["vocab:100143"]) -->|rdfs:label| 29(["''Priorité de l'actant''@fr"]):::Literal
