graph TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["vocab:100180"]):::E55_Type_URI -->|rdf:type| 1["crm:E55_Type"]:::E55_Type
2(["vocab:1001"]) -->|rdfs:label| 3(["''1''@en"]):::Literal
2(["vocab:1001"]) -->|rdfs:label| 4(["''1''@fr"]):::Literal
5(["actor:0001_100"]):::E39_Actor_URI -->|rdf:type| 6["crm:E21_Person"]:::E39_Actor
7(["-"]):::PC0_Typed_CRM_Property_URI -->|rdf:type| 8["crm:PC14_carried_out_by"]:::PC0_Typed_CRM_Property
2(["vocab:1001"]) -->|crm:P2_has_type| 9(["vocab:100143"])
0(["vocab:100180"]) -->|rdfs:label| 10(["''Creator''@en"]):::Literal
11(["-"]) -->|crm:P82b_end_of_the_end| 12(["''1938-12-31T23:59:59''^^xsd:dateTime"]):::Literal
2(["vocab:1001"]):::E55_Type_URI -->|rdf:type| 13["crm:E55_Type"]:::E55_Type
7(["-"]) -->|crm:P14.1_in_the_role_of| 0(["vocab:100180"])
0(["vocab:100180"]) -->|crm:P2_has_type| 14(["vocab:100144"])
14(["vocab:100144"]):::E55_Type_URI -->|rdf:type| 15["crm:E55_Type"]:::E55_Type
16(["object:0001_500"]):::E18_Physical_Thing_URI -->|rdf:type| 17["crm:E22_Human-Made_Object"]:::E18_Physical_Thing
9(["vocab:100143"]) -->|rdfs:label| 18(["''Actor Priority''@en"]):::Literal
0(["vocab:100180"]) -->|rdfs:label| 19(["''Créateur / Créatrice''@fr"]):::Literal
11(["-"]) -->|crm:P82a_begin_of_the_begin| 20(["''1938-01-01T00:00:00''^^xsd:dateTime"]):::Literal
7(["-"]) -->|crm:P02_has_range| 5(["actor:0001_100"])
14(["vocab:100144"]) -->|rdfs:label| 21(["''Actor Role''@en"]):::Literal
9(["vocab:100143"]):::E55_Type_URI -->|rdf:type| 22["crm:E55_Type"]:::E55_Type
23(["vocab:3003"]):::E53_Place_URI -->|rdf:type| 24["crm:E53_Place"]:::E53_Place
25(["-"]) -->|crm:P4_has_time-span| 11(["-"])
16(["object:0001_500"]) -->|rdfs:label| 26(["''Self-Portrait''@en"]):::Literal
14(["vocab:100144"]) -->|rdfs:label| 27(["''Rôle de l'actant''@fr"]):::Literal
5(["actor:0001_100"]) -->|rdfs:label| 28(["''Yousuf Karsh (1908-2002)''@en"]):::Literal
7(["-"]) -->|crm:P14.1_in_the_role_of| 2(["vocab:1001"])
25(["-"]) -->|crm:P7_took_place_at| 23(["vocab:3003"])
25(["-"]) -->|crm:P01i_is_domain_of| 7(["-"])
16(["object:0001_500"]) -->|crm:P108i_was_produced_by| 25(["-"])
23(["vocab:3003"]) -->|rdfs:label| 29(["''Ottawa, CA-ON''@fr"]):::Literal
11(["-"]):::E52_Time-Span_URI -->|rdf:type| 30["crm:E52_Time-Span"]:::E52_Time-Span
23(["vocab:3003"]) -->|rdfs:label| 31(["''Ottawa, CA-ON''@en"]):::Literal
25(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 32["crm:E12_Production"]:::E2_Temporal_Entity
9(["vocab:100143"]) -->|rdfs:label| 33(["''Priorité de l'actant''@fr"]):::Literal
