flowchart TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["actor:0001_122"]) -->|rdfs:label| 1(["''Diana Spencer''@en"]):::Literal
0(["actor:0001_122"]) -->|crm:P143i_was_joined_by| 2(["-"])
2(["-"]) -->|crm:P4_has_time-span| 3(["-"])
4(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 5["crm:E86_Leaving"]:::E2_Temporal_Entity
6(["actor:0001_123"]) -->|rdfs:label| 7(["''Famille royale britannique''@fr"]):::Literal
6(["actor:0001_123"]) -->|rdfs:label| 8(["''British royal family''@en"]):::Literal
2(["-"]) -->|crm:P144_joined_with| 6(["actor:0001_123"])
0(["actor:0001_122"]):::E39_Actor_URI -->|rdf:type| 9["crm:E21_Person"]:::E39_Actor
3(["-"]) -->|crm:P82b_end_of_the_end| 10(["''1981-12-31T23:59:59''^^xsd:dateTime"]):::Literal
11(["-"]):::E52_Time-Span_URI -->|rdf:type| 12["crm:E52_Time-Span"]:::E52_Time-Span
4(["-"]) -->|crm:P4_has_time-span| 11(["-"])
6(["actor:0001_123"]):::E39_Actor_URI -->|rdf:type| 13["crm:E74_Group"]:::E39_Actor
2(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 14["crm:E85_Joining"]:::E2_Temporal_Entity
3(["-"]):::E52_Time-Span_URI -->|rdf:type| 15["crm:E52_Time-Span"]:::E52_Time-Span
3(["-"]) -->|crm:P82a_begin_of_the_begin| 16(["''1981-01-01T00:00:00''^^xsd:dateTime"]):::Literal
4(["-"]) -->|crm:P146_separated_from| 6(["actor:0001_123"])
11(["-"]) -->|crm:P82b_end_of_the_end| 17(["''1996-12-31T23:59:59''^^xsd:dateTime"]):::Literal
11(["-"]) -->|crm:P82a_begin_of_the_begin| 18(["''1996-01-01T0:00:00''^^xsd:dateTime"]):::Literal
0(["actor:0001_122"]) -->|crm:P145i_left_by| 4(["-"])
