graph TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["-"]):::E52_Time-Span_URI -->|rdf:type| 1["crm:E52_Time-Span"]:::E52_Time-Span
2(["-"]) -->|crm:P146_separated_from| 3(["actor:0001_112"])
0(["-"]) -->|crm:P82a_begin_of_the_begin| 4(["''1933-01-01T00:00:00''^^xsd:dateTime"]):::Literal
5(["actor:0001_113"]) -->|crm:P143i_was_joined_by| 6(["-"])
3(["actor:0001_112"]) -->|rdfs:label| 7(["''Canadian Group of Painters (1933-1969)''@en"]):::Literal
2(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 8["crm:E86_Leaving"]:::E2_Temporal_Entity
5(["actor:0001_113"]) -->|rdfs:label| 9(["''A. J. Casson''@en"]):::Literal
6(["-"]) -->|crm:P01i_is_domain_of| 10(["-"])
6(["-"]) -->|crm:P4_has_time-span| 0(["-"])
10(["-"]) -->|crm:P02_has_range| 3(["actor:0001_112"])
5(["actor:0001_113"]):::E39_Actor_URI -->|rdf:type| 11["crm:E21_Person"]:::E39_Actor
3(["actor:0001_112"]):::E39_Actor_URI -->|rdf:type| 12["crm:E74_Group"]:::E39_Actor
10(["-"]):::PC0_Typed_CRM_Property_URI -->|rdf:type| 13["crm:PC144_joined_with"]:::PC0_Typed_CRM_Property
0(["-"]) -->|crm:P82b_end_of_the_end| 14(["''1933-12-31T23:59:59''^^xsd:dateTime"]):::Literal
6(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 15["crm:E85_Joining"]:::E2_Temporal_Entity
5(["actor:0001_113"]) -->|crm:P145i_left_by| 2(["-"])
