flowchart TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["vocab:3007"]) -->|rdfs:label| 1(["''Montreal, CA-QC''@en"]):::Literal
2(["-"]) -->|crm:P82b_end_of_the_end| 3(["''1974-12-31T23:59:59''^^xsd:dateTime"]):::Literal
4(["-"]) -->|crm:P4_has_time-span| 2(["-"])
2(["-"]):::E52_Time-Span_URI -->|rdf:type| 5["crm:E52_Time-Span"]:::E52_Time-Span
6(["actor:0001_109"]):::E39_Actor_URI -->|rdf:type| 7["crm:E21_Person"]:::E39_Actor
4(["-"]) -->|crm:P7_took_place_at| 0(["vocab:3007"])
4(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 8["crm:E67_Birth"]:::E2_Temporal_Entity
2(["-"]) -->|crm:P82a_begin_of_the_begin| 9(["''1974-01-01T00:00:00''^^xsd:dateTime"]):::Literal
0(["vocab:3007"]) -->|rdfs:label| 10(["''Montréal, CA-QC''@fr"]):::Literal
6(["actor:0001_109"]) -->|crm:P98i_was_born| 4(["-"])
6(["actor:0001_109"]) -->|rdfs:label| 11(["''David Altmejd (1974-)''@en"]):::Literal
0(["vocab:3007"]):::E53_Place_URI -->|rdf:type| 12["crm:E53_Place"]:::E53_Place
