graph TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["actor:0001_105"]) -->|rdfs:label| 1(["''Massih Karsh''@en"]):::Literal
2(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 3["crm:E69_Death"]:::E2_Temporal_Entity
4(["-"]) -->|crm:P96_by_mother| 5(["actor:0001_104"])
6(["vocab:3001"]):::E53_Place_URI -->|rdf:type| 7["crm:E53_Place"]:::E53_Place
8(["-"]):::E52_Time-Span_URI -->|rdf:type| 9["crm:E52_Time-Span"]:::E52_Time-Span
2(["-"]) -->|crmarcheo:AP28_occurs_before| 10(["-"])
11(["vocab:3004"]):::E53_Place_URI -->|rdf:type| 12["crm:E53_Place"]:::E53_Place
13(["vocab:3002"]) -->|rdfs:label| 14(["''Boston, USA-MA''@fr"]):::Literal
10(["-"]) -->|crm:P26_moved_to| 11(["vocab:3004"])
15(["vocab:100146"]):::E55_Type_URI -->|rdf:type| 16["crm:E55_Type"]:::E55_Type
17(["actor:0001_100"]):::E39_Actor_URI -->|rdf:type| 18["crm:E21_Person"]:::E39_Actor
13(["vocab:3002"]):::E53_Place_URI -->|rdf:type| 19["crm:E53_Place"]:::E53_Place
20(["-"]) -->|crm:P82b_end_of_the_end| 21(["''2002-07-13T23:59:59''^^xsd:dateTime"]):::Literal
6(["vocab:3001"]) -->|rdfs:label| 22(["''Mardin (Ottoman Empire)''@en"]):::Literal
20(["-"]) -->|crm:P82a_begin_of_the_begin| 23(["''2002-07-13T00:00:00''^^xsd:dateTime"]):::Literal
2(["-"]) -->|crm:P7_took_place_at| 13(["vocab:3002"])
8(["-"]) -->|crm:P82a_begin_of_the_begin| 24(["''1908-12-23T00:00:00''^^xsd:dateTime"]):::Literal
13(["vocab:3002"]) -->|rdfs:label| 25(["''Boston, USA-MA''@en"]):::Literal
17(["actor:0001_100"]) -->|crm:P98i_was_born| 4(["-"])
15(["vocab:100146"]) -->|rdfs:label| 26(["''Lieu de sépulture''@fr"]):::Literal
0(["actor:0001_105"]):::E39_Actor_URI -->|rdf:type| 27["crm:E21_Person"]:::E39_Actor
10(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 28["crm:E9_Move"]:::E2_Temporal_Entity
4(["-"]) -->|crm:P7_took_place_at| 6(["vocab:3001"])
20(["-"]):::E52_Time-Span_URI -->|rdf:type| 29["crm:E52_Time-Span"]:::E52_Time-Span
6(["vocab:3001"]) -->|rdfs:label| 30(["''Mardin (Empire ottoman)''@fr"]):::Literal
17(["actor:0001_100"]) -->|rdfs:label| 31(["''Yousuf Karsh (1908-2002)''@en"]):::Literal
5(["actor:0001_104"]):::E39_Actor_URI -->|rdf:type| 32["crm:E21_Person"]:::E39_Actor
15(["vocab:100146"]) -->|rdfs:label| 33(["''Burial Place''@en"]):::Literal
11(["vocab:3004"]) -->|crm:P2_has_type| 15(["vocab:100146"])
4(["-"]) -->|crm:P97_from_father| 0(["actor:0001_105"])
10(["-"]) -->|crm:P25_moved| 17(["actor:0001_100"])
4(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 34["crm:E67_Birth"]:::E2_Temporal_Entity
8(["-"]) -->|crm:P82b_end_of_the_end| 35(["''1908-12-23T:23:59:59''^^xsd:dateTime"]):::Literal
5(["actor:0001_104"]) -->|rdfs:label| 36(["''Bahiyah Nakash''@en"]):::Literal
10(["-"]) -->|crm:P27_moved_from| 13(["vocab:3002"])
2(["-"]) -->|crm:P4_has_time-span| 20(["-"])
17(["actor:0001_100"]) -->|crm:P100i_died_in| 2(["-"])
11(["vocab:3004"]) -->|rdfs:label| 37(["''Notre-Dame Cemetery (Ottawa, CA-ON)''@en"]):::Literal
11(["vocab:3004"]) -->|rdfs:label| 38(["''Cimetière Notre-Dame (Ottawa, CA-ON)''@fr"]):::Literal
4(["-"]) -->|crm:P4_has_time-span| 8(["-"])
