flowchart TD
classDef Literal fill:#ffffff,stroke:#000000;
classDef Literal_URI fill:,stroke:;
classDef E1_CRM_Entity fill:#ffffff,stroke:#000000;
classDef E1_CRM_Entity_URI fill:#ffffff,stroke:#000000;
classDef E2_Temporal_Entity fill:#82c3ec,stroke:#000000;
classDef E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef E55_Type fill:#fab565,stroke:#000000;
classDef E55_Type_URI fill:#fde7ce,stroke:#000000;
classDef E52_Time-Span fill:#86bcc8,stroke:#000000;
classDef E52_Time-Span_URI fill:#dcebef,stroke:#000000;
classDef E41_Appellation fill:#fef3ba,stroke:#000000;
classDef E41_Appellation_URI fill:#fffae6,stroke:#000000;
classDef E53_Place fill:#94cc7d,stroke:#000000;
classDef E53_Place_URI fill:#e1f1da,stroke:#000000;
classDef E77_Persistent_Item fill:#ffffff,stroke:#000000;
classDef E77_Persistent_Item_URI fill:#ffffff,stroke:#000000;
classDef E28_Conceptual_Object fill:#fddc34,stroke:#000000;
classDef E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef E18_Physical_Thing fill:#e1ba9c,stroke:#000000;
classDef E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef E39_Actor fill:#ffbdca,stroke:#000000;
classDef E39_Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000;
classDef PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;
0(["actor:0001_106"]) -->|crm:P100i_died_in| 1(["-"])
1(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 2["crm:E69_Death"]:::E2_Temporal_Entity
1(["-"]) -->|crm:P4_has_time-span| 3(["-"])
3(["-"]) -->|crm:P82a_begin_of_the_begin| 4(["''1945-03-02T00:00:00''^^xsd:dateTime"]):::Literal
5(["vocab:3005"]) -->|rdfs:label| 6(["''Victoria, CA-BC''@en"]):::Literal
7(["-"]):::E52_Time-Span_URI -->|rdf:type| 8["crm:E52_Time-Span"]:::E52_Time-Span
9(["vocab:100146"]):::E55_Type_URI -->|rdf:type| 10["crm:E55_Type"]:::E55_Type
0(["actor:0001_106"]):::E39_Actor_URI -->|rdf:type| 11["crm:E21_Person"]:::E39_Actor
12(["vocab:3006"]):::E53_Place_URI -->|rdf:type| 13["crm:E53_Place"]:::E53_Place
14(["actor:0001_107"]) -->|rdfs:label| 15(["''Emily (Saunders) Carr''@en"]):::Literal
16(["-"]) -->|crm:P25_moved| 0(["actor:0001_106"])
7(["-"]) -->|crm:P82b_end_of_the_end| 17(["''1871-12-13T23:59:59''^^xsd:dateTime"]):::Literal
16(["-"]) -->|crm:P27_moved_from| 5(["vocab:3005"])
18(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 19["crm:E67_Birth"]:::E2_Temporal_Entity
18(["-"]) -->|crm:P4_has_time-span| 7(["-"])
20(["actor:0001_108"]):::E39_Actor_URI -->|rdf:type| 21["crm:E21_Person"]:::E39_Actor
0(["actor:0001_106"]) -->|rdfs:label| 22(["''Emily Carr (1871-1945)''@en"]):::Literal
18(["-"]) -->|crm:P7_took_place_at| 5(["vocab:3005"])
18(["-"]) -->|crm:P97_from_father| 20(["actor:0001_108"])
20(["actor:0001_108"]) -->|rdfs:label| 23(["''Richard Carr''@en"]):::Literal
16(["-"]) -->|crm:P26_moved_to| 12(["vocab:3006"])
9(["vocab:100146"]) -->|rdfs:label| 24(["''Lieu de sépulture''@fr"]):::Literal
1(["-"]) -->|crmarcheo:AP28_occurs_before| 16(["-"])
18(["-"]) -->|crm:P96_by_mother| 14(["actor:0001_107"])
12(["vocab:3006"]) -->|crm:P2_has_type| 9(["vocab:100146"])
16(["-"]):::E2_Temporal_Entity_URI -->|rdf:type| 25["crm:E9_Move"]:::E2_Temporal_Entity
12(["vocab:3006"]) -->|rdfs:label| 26(["''Cimetière de Ross Bay (Victoria, CA-BC)''@fr"]):::Literal
5(["vocab:3005"]):::E53_Place_URI -->|rdf:type| 27["crm:E53_Place"]:::E53_Place
14(["actor:0001_107"]):::E39_Actor_URI -->|rdf:type| 28["crm:E21_Person"]:::E39_Actor
3(["-"]):::E52_Time-Span_URI -->|rdf:type| 29["crm:E52_Time-Span"]:::E52_Time-Span
0(["actor:0001_106"]) -->|crm:P98i_was_born| 18(["-"])
9(["vocab:100146"]) -->|rdfs:label| 30(["''Burial Place''@en"]):::Literal
5(["vocab:3005"]) -->|rdfs:label| 31(["''Victoria, CA-BC''@fr"]):::Literal
3(["-"]) -->|crm:P82b_end_of_the_end| 32(["''1945-03-02T23:59:59''^^xsd:dateTime"]):::Literal
1(["-"]) -->|crm:P7_took_place_at| 5(["vocab:3005"])
12(["vocab:3006"]) -->|rdfs:label| 33(["''Ross Bay Cemetery (Victoria, CA-BC)''@en"]):::Literal
7(["-"]) -->|crm:P82a_begin_of_the_begin| 34(["''1871-12-13T00:00:00''^^xsd:dateTime"]):::Literal
