# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DOPHEDA
titre: DOPHEDA
email: pch.RCIP-CHIN.pch@canada.ca
description: >- # this means to ignore newlines until "baseurl:"
  All the documentation pertaining to DOPHEDA developed by CHIN.
  Toute la documentation à propos de DOPHEDA développé par le RCIP.
baseurl: "/collections-model" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  chin-rcip

# Build settings
theme: minima
plugins:
  - jekyll-feed
header_pages_en:
  - en/about.md
  - en/licensing-documentation.md
  - en/tm/current/02-introduction.md
  - en/sps/current/01-introduction.md
  - en/resources/current/cidoc-crm-tutorial.md
  - en/resources/current/glossary.md
  - en/resources/current/lod-benefits-challenges.md
  - en/resources/current/tools.md
  - en/resources/current/how-to/diagrams-net.md
  - en/resources/current/how-to/criteria.md
  - en/reports/current/ng-report-1.md
  - en/reports/current/uris-technical-report.md
header_pages_fr:
  - fr/a-propos.md
  - fr/licence.md
  - fr/mc/actuel/02-introduction.md
  - fr/scs/actuel/01-introduction.md
  - fr/ressources/actuel/lod-avantages-defis.md
  - fr/ressources/actuel/glossaire.md
  - fr/ressources/actuel/outils.md
  - fr/ressources/actuel/tutoriel-cidoc-crm.md
  - fr/ressources/actuel/mode-demploi/diagrams-net.md
  - fr/ressources/actuel/mode-demploi/criteria.md
  - fr/rapports/actuel/gn-rapport-1.md
  - fr/rapports/actuel/rapport-technique-uris.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
